[package]
name = "m-bus-parser-cli"
version = "0.0.0"
edition = "2021"
description = "A cli to use the library for parsing M-Bus frames"
license = "MIT"
homepage = "https://maebli.github.io/"
repository = "https://github.com/maebli/m-bus-parser"
readme = "README.md"
author = "Michael Aebli"
keywords = ["m-bus", "parser", "parse", "cli"]

[dev-dependencies]

[build-dependencies]

[features]

[profile.release]
opt-level = 'z'   # Optimize for size
lto = true        # Enable Link Time Optimization
codegen-units = 1 # Reduce codegen units to improve optimizations

[dependencies]
m-bus-parser = { path = "..", version = "0.0.3" }
clap = "4.5.4"
